/**
 to make it work properly, this part should be added to gulpfile.js
in ./src/_pages/general_page.pug add this lines at the end of the file:

	style
		include ./all_style.css

all_style.css - is a file with all styles from ./src/css/ folder generated by gulp
name of this file can be changed in gulpfile.js by changing pug_styles_file variable
 */


// region build pug + styles + js

// directory with general-page pug file
const pages_dir = './src/_pages/';
// directory where to put result of pug compilation
const pug_result_dir = './prod/';
// name of file with all styles that will be used in general-page.pug to include styles from ./src/css/ folder
const pug_styles_file = "all_style.css"

// process general-page.pug file from ./src/_pages/ folder
function processPagesPug() {
	return gulp.src(pages_dir + '*.pug')
				.pipe(pug({
					pretty: true,
				}))
				.pipe(gulp.dest(pug_result_dir));
}

// process styles from ./src/css/ folder and put them into one file that will be included in general-page.pug
// created file is not needed for production, it is used only for build pug
function processPagesPugStyles() {
	return gulp.src(cssFiles)
		.pipe(sass.sync().on('error', sass.logError))
		.pipe(concat(pug_styles_file))
		.pipe(autoprefixer({
			cascade: false
		}))
		// .pipe(cleanCSS({
		// 	level: 0
		// }))
		.pipe(gulp.dest(pages_dir))
		.pipe(browserSync.stream());
}

// clean file with all styles that was created for build pug
function cleanPagesPugBuild() {
	return del([pages_dir + pug_styles_file]);
}

gulp.task('processPagesPug', processPagesPug);
gulp.task('processPagesPugStyles', processPagesPugStyles);
gulp.task('cleanPagesPugBuild', cleanPagesPugBuild);

gulp.task('stage', gulp.series(processPagesPugStyles, processPagesPug, cleanPagesPugBuild));

// end build pug + styles + js